title: "Reuben Tamakloe, PhD"
author: "Reuben Tamakloe"
email: "drtamakloe@kaist.ac.kr"
description: >-
  Academic portfolio and research website of Reuben Tamakloe. Assistant Research Professor at the Cho Chun Shik Graduate School of Mobility, KAIST.
  Last Update - 12 May 2026
affiliation: "Cho Chun Shik Graduate School of Mobility, Korea Advanced Institute of Science and Technology (KAIST)"
url: "https://drtamakloe.github.io"
show_downloads: false

theme: minima

twitter_username: drtamakloe
linkedin_username: drtamakloe
instagram_username: drtamakloe

google_scholar: "https://scholar.google.com/citations?user=2V3gP2EAAAAJ&hl=en"
scopus: "https://www.scopus.com/authid/detail.uri?authorId=57206723737"
orcid: "https://orcid.org/0000-0002-9605-8439"

google_analytics: G-G58P7X4Y1K

plugins:
  - jekyll-feed
  - jekyll-seo-tag
